import { z } from "zod";

/**
 * Playing status enum matching backend PlayingStatus
 */
export const PlayingStatusSchema = z.enum(["active", "retired", "free_agent"]);

/**
 * Base player schema with shared validation rules
 * Used as the foundation for both Player and PlayerCreate schemas
 */
const PlayerBaseSchema = z.object({
  full_name: z
    .string()
    .min(2, "Full name must be at least 2 characters")
    .max(100, "Full name cannot exceed 100 characters"),
  country: z
    .string()
    .min(2, "Country must be at least 2 characters")
    .max(50, "Country cannot exceed 50 characters"),
  status: PlayingStatusSchema,
  current_team: z
    .string()
    .max(100, "Current team cannot exceed 100 characters")
    .nullable()
    .optional(),
  league: z
    .string()
    .max(100, "League cannot exceed 100 characters")
    .nullable()
    .optional(),
  age: z
    .number()
    .int("Age must be an integer")
    .min(0, "Age must be at least 0")
    .max(120, "Age cannot exceed 120"),
  market_value: z
    .number()
    .int("Market value must be an integer")
    .min(0, "Market value cannot be negative")
    .max(10_000_000_000, "Market value cannot exceed 10 billion USD")
    .nullable()
    .optional(),
});

/**
 * Player schema - response model from backend
 * Includes auto-generated ID
 */
export const PlayerSchema = PlayerBaseSchema.extend({
  id: z.number().int("ID must be an integer"),
});

/**
 * PlayerCreate schema - DTO for creating a new player
 * Excludes ID (auto-generated by server)
 * All validations match backend PlayerCreate model
 */
export const PlayerCreateSchema = PlayerBaseSchema;

// Type exports for TypeScript usage
export type Player = z.infer<typeof PlayerSchema>;
export type PlayerCreate = z.infer<typeof PlayerCreateSchema>;
export type PlayingStatus = z.infer<typeof PlayingStatusSchema>;
